apiVersion: apps/v1
kind: Deployment
metadata:
      name: shoppingdeployment
spec:
     replicas: 1
     selector:
        matchLabels:
             app: shop
     template:
        metadata:
            labels:
               app: shop
        spec:
          containers:
          - name: flipkartapp
            image: devopschand/shopping
            ports:
            - containerPort: 8080
            resources:
               requests:
                  cpu: 200m
                  memory: 250Mi
               limits:
                 cpu: 500m
                 memory: 500Mi
---
apiVersion: v1
kind: Service
metadata:
    name: shopservice
spec:
    selector:
       app: shop
    type: NodePort
    ports:
    - port: 8082
      targetPort: 8080
